### PR TITLE
Add support for AssumeRole in AWS

### PR DESCRIPTION
**Pull request by ystros**
AWS supports the concept of "assume role" where one account can be granted temporary credentials to another approved account. This PR adds the ability to specify the role ARN to use with AssumeRole when dealing with an S3 backend for metalinks.

More information about assume role:
https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html

This PR also updates the project to the latest version of Golang and converts it to use Go modules.

A potentially breaking change as part of the Golang upgrade is the format for `git+ssh` sources. Previously, metalink accepted values like `git+ssh://git@github.com:cloudfoundry/bosh-compiled-releases-index`. In the previous version of Golang used, this string was parseable by `uri.Parse` even though it is not a valid URI. In the newer versions of Golang, this results in an error. To get around the error, we've opted to change the format to something more like `git+ssh://git@github.com/cloudfoundry/bosh-compiled-releases-index` (a `/` instead of a `:` after github) rather than write our own parser. This new format is actually what was documented previously, so it's unclear of accepting the `:` version before was intentional.

Once merged, we will submit a similar PR to update the [concourse resource](https://github.com/dpb587/metalink-repository-resource)

### CODE REVIEW

**Comment by dpb587** [comment]
Hi - thanks for the commits. A few thoughts...

Good catch on the `url.Parse` upstream change. I think the colon-syntax should continue to be supported, though. A narrow regex would probably be sufficient and easy enough to add to help maintain compatibility - what do you think? Otherwise it'll be a breaking change and I think quite a few pipelines would start failing and need to be reconfigured and probably backported in some cases, including cloudfoundry ones ([public code search](https://github.com/search?q=%22metalink-repository-resource%22+%28path%3A*.yml+OR+path%3A*.yaml%29&type=code)).

Were you already able to test these changes locally to make sure the assume role is fully working as expected? e.g. `AWS_*=... go run ./repository/cli filter 's3://...'`.

Do you think we still need to keep the manually-sync’d vendor directory? I can delete it in a follow-up commit unless you have any objections or want to add it to the pull.

**Comment by dpb587** [comment]
FWIW, I saw there was some old, unrelated code causing some build and test issues. I went ahead and fixed them and would rebase them after the PR. I pushed it to a branch rather than clutter up this PR, but [these are the changes](https://github.com/dpb587/metalink/compare/ystros:add-assume-role-support...pr-6-post), if helpful in the meantime or you want to pull them in locally or to the PR.

**Comment by ystros** [comment]
Thanks for the quick response and review!

We can add back support for the colon-syntax; our original plan was to update all of the usages in cloudfoundry, but there do appear to be a couple projects outside that which could potentially break.

We've done some manual testing both with the `metalink` CLI directly as you suggest, and with a version of the Concourse resource, which worked as expected when passed assume role configurations. If you're curious, you look at the changes to the [corresponding resource changes](https://github.com/dpb587/metalink-repository-resource/compare/master...ystros:metalink-repository-resource:add-assume-role-support). The only thing not pushed there is a `replace github.com/dpb587/metalink v0.3.1-0.20190430040746-578c916bbfbd => ../metalink` line in go.mod to enable building it with our changes.

Happy to remove the `vendor` directories from both PRs.

**Comment by ystros** [comment]
Hi @dpb587! I've updated the existing commits to remove the vendor directory, and added back in support for the git-clone formatted colon syntax by checking specifically for `git+ssh` and parsing it via regex instead. 

Let me know what you think!

**Comment by dpb587** [comment]
Hi @ystros - I merged and tagged a [v0.5.0 release](https://github.com/dpb587/metalink/releases/tag/v0.5.0) with your PR and a couple other minor changes. Thanks!

**Pull request merged**
